language: node_js
cache:
  directories:
    - node_modules
os:
  - linux
  - osx
before_install:
  - npm install -g --no-progress npm@latest
install:
  - npm install --no-progress
script:
  - npm run editorconfig-tools-check
  - npm test -- -R dot --check-leaks
  - npm run coveralls
  - npm run build
